### ISSUE TITLE
TemplateNotFound: data_title.txt

### ISSUE THREAD

**Issue by ma-diroma** [ERGA-consortium/ERGA-submission#3]
Hi,

I am trying to use your get_ENA_xml_files.py. My python is v.3.10.12, pandas and jinja2 have been installed.

When I launch the command 

`python get_ENA_xml_files.py -f examples/fValHis.BGE.runs.tsv -p ERGA-BGE -o fValHis1`

I get this error

```
Traceback (most recent call last):
  File "/home/mdiroma/bin/ERGA-submission/get_submission_xmls/get_ENA_xml_files.py", line 501, in <module>
    get_studies(
  File "/home/mdiroma/bin/ERGA-submission/get_submission_xmls/get_ENA_xml_files.py", line 100, in get_studies
    study_title = env.get_template("data_title.txt").render(
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: data_title.txt
```

I verified, the data_title.txt is in the folder templates.
Could you please help me?

Thanks,
Maria Angela

**Comment by talioto** [comment]
I installed from scratch and confirm the bug. I will see if I can debug it without Jessica...

**Comment by talioto** [comment]
OK, so for now give the full path to the script, like: 
`python3 /Users/talioto/repositories/ERGA-submission/get_submission_xmls/get_ENA_xml_files.py -f examples/fValHis.BGE.runs.tsv -p ERGA-BGE -o fValHis1`
We need to fix it so that it can find the templates relative to the script or use environment variables. Sorry for the non-intuitive behavior.

**Comment by ma-diroma** [comment]
It works, thank you!

**Comment by tbrown91** [comment]
Thanks @talioto
